// Creates or upgrades the database tables. Usage: npm run db:migrate
import { migrateActionCards } from "../src/action-cards/index";
import { migrateAgentRunLog } from "../src/agent-runs/index";
import { migrateApplications } from "../src/applications/index";
import { migrateAtsScores } from "../src/ats-score/index";
import { authConfigFromEnv } from "../src/auth/config";
import { migrateCandidateAccounts } from "../src/auth/index";
import { migrateCompanyDossiers } from "../src/company-dossiers/index";
import { migrateJobDigests } from "../src/job-digests/index";
import { migrateJobOffers } from "../src/job-offers/index";
import { migrateJobSearches } from "../src/job-searches/index";
import { migrateProfiles } from "../src/profiles/index";
import { migrateBilling } from "../src/billing/index";
import { migrateTailoredDocuments } from "../src/tailored-documents/index";

const config = authConfigFromEnv(process.env);
await migrateCandidateAccounts(config);
console.info("[migrate] Candidate accounts are up to date");
await migrateAgentRunLog(config.database);
console.info("[migrate] Agent Run log is up to date");
await migrateProfiles(config.database);
console.info("[migrate] Profiles are up to date");
await migrateJobOffers(config.database);
console.info("[migrate] Job Offers are up to date");
await migrateApplications(config.database);
console.info("[migrate] Applications are up to date");
await migrateCompanyDossiers(config.database);
console.info("[migrate] Company Dossiers are up to date");
await migrateTailoredDocuments(config.database);
console.info("[migrate] Cover Letters and Outreach Messages are up to date");
await migrateActionCards(config.database);
console.info("[migrate] Action Cards are up to date");
await migrateAtsScores(config.database);
console.info("[migrate] ATS Scores are up to date");
await migrateBilling(config.database);
console.info("[migrate] Plans and Plan Quotas are up to date");
await migrateJobSearches(config.database);
console.info("[migrate] Job Searches are up to date");
await migrateJobDigests(config.database);
console.info("[migrate] Job Digests are up to date");
await config.database.end();
