#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
# ask_price KEY "Prompt" is like ask, for a Stripe price ID: it re-asks until
# the value starts with price_ (or is left empty), and explains the usual
# mix-up with a product ID (prod_…). Gives up after a few tries.
ask_price() {
  local key="$1" prompt="$2" value tries=0
  while :; do
    ask "$key" "$prompt"
    value="${!key}"
    [[ -z "$value" || "$value" == price_* ]] && return 0
    if [[ "$value" == prod_* ]]; then
      warn "That is a product ID (prod_…), not a price ID. A product can have several prices;"
      warn "open the product in Stripe, click its price, and copy the ID that starts with price_."
    else
      warn "A Stripe price ID starts with price_. Copy it from the price's page in Stripe."
    fi
    tries=$((tries + 1))
    (( tries < 5 )) || { warn "No price ID entered; re-run the wizard when you have it."; exit 1; }
  done
}

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Plans and billing (issue #22, ADR-0014). Configures Stripe in TEST
# mode and the back office for local development. Run from the repo root:
#   bash scripts/setup/issue-22.sh            (writes ./.env)
#   ENV_FILE=path/to/.env bash scripts/setup/issue-22.sh
# For production, repeat the same steps in Stripe's live mode and put the
# values in the production environment instead of .env.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Jobbbox: Stripe billing and back-office setup (issue #22)"

stage "Stripe account in test mode"
say "Jobbbox bills the Standard and Premium Plans through Stripe."
open_url "https://dashboard.stripe.com/register"
step "Sign in to Stripe, or create an account for Jobbbox if there is none yet."
step "Switch the dashboard to Test mode (the toggle in the top bar)."
note "Everything below happens in test mode: a live key is refused outside production."
pause "Done? Press Enter"

stage "Stripe: secret API key"
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the 'Secret key' row, click 'Reveal test key' and copy it (starts sk_test_)."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
if [[ "$STRIPE_SECRET_KEY" != sk_test_* && "$STRIPE_SECRET_KEY" != rk_test_* ]]; then
  warn "That doesn't look like a test-mode key (sk_test_…). Outside production the app refuses live keys."
  confirm "Save it anyway?" || { warn "Re-run the wizard with a test key."; exit 1; }
fi
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"

stage "Stripe: the Standard and Premium Prices"
open_url "https://dashboard.stripe.com/test/products/create"
step "Create a product named 'Jobbbox Standard' with a recurring, monthly price."
step "Save it, open the price and copy its ID (starts price_)."
ask_price STRIPE_PRICE_STANDARD "Paste the Standard monthly price ID:"
write_env STRIPE_PRICE_STANDARD "$STRIPE_PRICE_STANDARD"
step "Create a second product, 'Jobbbox Premium', with a recurring monthly price, and copy its price ID."
ask_price STRIPE_PRICE_PREMIUM "Paste the Premium monthly price ID:"
write_env STRIPE_PRICE_PREMIUM "$STRIPE_PRICE_PREMIUM"
note "The amounts are a business decision: Jobbbox reads the Plan from the price ID only."

stage "Stripe: customer portal"
say "Candidates manage invoices, payment method, Plan changes and cancellation in Stripe's portal."
open_url "https://dashboard.stripe.com/test/settings/billing/portal"
step "Turn on: invoice history, update payment method, cancel subscriptions."
step "Turn on 'Customers can switch plans' and add both products (Standard and Premium) with their monthly prices."
step "Save the portal configuration."
pause "Done? Press Enter"

stage "Stripe: webhook signing secret"
say "Plans follow Stripe: the app only changes a Candidate's Plan from signed webhooks."
say "The app listens on {APP_URL}/api/billing/webhook for:"
note "  customer.subscription.created, customer.subscription.updated, customer.subscription.deleted"
if confirm "Is this for local development with the Stripe CLI (stripe listen)?"; then
  open_url "https://docs.stripe.com/stripe-cli"
  step "Install the Stripe CLI and run: stripe login"
  step "Then, in another terminal, keep this running while you use the app:"
  note "  stripe listen --events customer.subscription.created,customer.subscription.updated,customer.subscription.deleted --forward-to localhost:3000/api/billing/webhook"
  step "It prints 'Your webhook signing secret is whsec_…': copy it."
else
  open_url "https://dashboard.stripe.com/test/webhooks/create"
  step "Add an endpoint: {APP_URL}/api/billing/webhook (your deployed web app's URL)."
  step "Select the three customer.subscription events above, then create the endpoint."
  step "On the endpoint's page, reveal the 'Signing secret' and copy it (starts whsec_)."
fi
ask_secret STRIPE_WEBHOOK_SECRET "Paste the webhook signing secret:"
write_env STRIPE_WEBHOOK_SECRET "$STRIPE_WEBHOOK_SECRET"

stage "Back office: Administrators"
say "Administrators edit the Plan Quotas at /admin/quotas. They sign in like Candidates."
ask ADMIN_EMAILS "Administrators' email addresses, comma-separated:"
write_env ADMIN_EMAILS "$ADMIN_EMAILS"
note "Restart 'npm run dev' so the app reads the new values."

finish
